{% set name = "mafft" %}
{% set version = "7.526" %}

# recipe from bioconda https://github.com/bioconda/bioconda-recipes/blob/76794693913ab648d37f7c4d2ddc14413dd9d206/recipes/mafft/meta.yaml

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/sysimm/mafft/-/archive/v{{ version }}/mafft-v{{ version }}.zip
  sha256: "fde872598d880683fbf90da76c88275d7fa24c1fcdc3cc3791969434135257d7"

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
  run:
    - gawk

test:
  commands:
    - mafft --version

about:
  home: 'http://mafft.cbrc.jp/alignment/software/'
  license: BSD-3-Clause
  license_family: BSD
  license_file: license
  summary: Multiple alignment program for amino acid or nucleotide sequences based on fast Fourier transform

extra:
  recipe-maintainers:
    - hmacdope
    - mikemhenry
